[mos-ci] Nova unit test requires /etc/machine-id
Without /etc/machine-id nova unit test fails with message:

nova.exception.NovaException: Unable to get host UUID: /etc/machine-id is empty

Change-Id: Ic897b50dec66ac686622907f2a5bde0fb3265413