Don't reinitialize existing virtualenv
We have pip specified in requirements.txt and update it during the `pip
install` run. Therefore, when we try to reinitialize venv we get older
version of pip installed on top of updated packages. Which causes the

  ImportError: cannot import name HeaderParsingError

Change-Id: Ib7a474b24f4d7ea5dc87f9a3e67ef4c7747adc3d