Remove redunant quotes in UPGRADE_FUEL_ variables
The quotas passed as plain-text into env variable which causes fail in
https://product-ci.infra.mirantis.net/view/upgrades/job/8.0.upgrades.ubuntu.upgrade_ceph_ha_tests/5/console
File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number ''8.0''

Change-Id: I8933b9cc15b5d3c746c3eb10b7b69b6a055effb7